#ifndef LISTENUMTRAITEMENTS_H_INCLUDED
#define LISTENUMTRAITEMENTS_H_INCLUDED

enum TREATMENTS
{
    ID_FILT_NONE = 1, // pas de filtre
    ID_FILT_BLUR,
    ID_FILT_MEDIAN,
    ID_FILT_CONV,
    ID_FILT_CANNY,
    ID_FILT_THRES,
    ID_FILT_ERODE,
    ID_FILT_DILATE
};

enum CONVOLUTION
{
    MEAN = 1,
    SHARPEN,
    LAPLACIEN,
    SOBEL_X,
    SOBEL_Y,
};

#endif // LISTENUMTRAITEMENTS_H_INCLUDED
